### ISSUE TITLE
close event not triggered

### ISSUE THREAD

**Issue by CramericaIndustries** [jenstornell/tinyDrawer.js#31]
The 'close' event is not fired, when the drawer is closed. 'open' event works, though.

suspect no1 is line #46 in the `.../src/tinyDrawer.js` file.
replacing `this.close();` with `this.close(e.target);` solved the issue for me.

**Comment by jenstornell** [comment]
Yes, you are right. Somewhere down the line, I lost the `e.target`. Thanks for your report and solution. I've updated it with your fix.
