### ISSUE TITLE
'open' event not fired

### ISSUE THREAD

**Issue by CramericaIndustries** [jenstornell/tinyDrawer.js#32]
The `open` event is not fired, when the drawer is opened using the `tinyDrawerOpen()` function.
Possibly same for the `close` event when using `tinyDrawerClose()` to close the drawer, but didn't test that.

**Comment by jenstornell** [comment]
That's strange. In my tests they both work with the latest version of the code.

![image](https://user-images.githubusercontent.com/927011/53229891-b5ca6000-3685-11e9-92da-e268d650ca76.png)

**Comment by CramericaIndustries** [comment]
Made a Plunker to demonstrate the problem
[https://plnkr.co/edit/UP4Oa1TnJSB9ctJAk45X?p=preview](https://plnkr.co/edit/UP4Oa1TnJSB9ctJAk45X?p=preview)

**Comment by jenstornell** [comment]
Now I understand what you mean. I did not read your issue carefully enough. It was not a super fast quickfix as I thought, but now it should work as expected.

**If you want to see the changes, here they are:** https://github.com/jenstornell/tinyDrawer.js/commit/7ce755ec23c56da96e574906225e82a29f7ed80d

By the way, if you need to get the clicked element in the callback, you also need to send the event like this: `tinyDrawerOpen(event)`.

If it works now you can close it if you want. Thanks for your report and sorry about the problems.

**Comment by CramericaIndustries** [comment]
It is working now. Big thanks for the quick fix!
