### ISSUE TITLE
WHY NO package.json?

### ISSUE THREAD

**Issue by S1SYPHOS** [jenstornell/tinyDrawer.js#33]
U NO `package.json`?

All jokes aside, why not make this available? Also, I'd be easier to contribute in terms of dependency management!

**Comment by jenstornell** [comment]
You mean you want Composer support? Or is there any other reason why the need of `package.json`?

**Comment by S1SYPHOS** [comment]
Not so much, but making it an NPM package, no?

**Comment by S1SYPHOS** [comment]
Making it an NPM package is too much effort then, I guess? :/
